.PHONY: clean All

All:
	@echo "----------Building project:[ RWA3-Group11 - Debug ]----------"
	@cd "RWA3-Group11" && "$(MAKE)" -f  "RWA3-Group11.mk"
clean:
	@echo "----------Cleaning project:[ RWA3-Group11 - Debug ]----------"
	@cd "RWA3-Group11" && "$(MAKE)" -f  "RWA3-Group11.mk" clean
