.PHONY: clean All

All:
	@echo "----------Building project:[ Final-Project-Group11 - Debug ]----------"
	@cd "Final-Project-Group11" && "$(MAKE)" -f  "Final-Project-Group11.mk"
clean:
	@echo "----------Cleaning project:[ Final-Project-Group11 - Debug ]----------"
	@cd "Final-Project-Group11" && "$(MAKE)" -f  "Final-Project-Group11.mk" clean
